/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch design system tokens
        "on-tertiary-fixed": "#341100",
        "secondary-container": "#e2e0fc",
        "surface-container-highest": "#e1e3e4",
        "on-error-container": "#93000a",
        "surface-container": "#edeeef",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "secondary": "#5d5c74",
        "on-primary": "#ffffff",
        "on-secondary-container": "#63627a",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-container": "#0e0200",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#414754",
        "on-secondary-fixed-variant": "#45455b",
        "inverse-primary": "#adc7ff",
        "surface": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "on-background": "#191c1d",
        "on-secondary-fixed": "#1a1a2e",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#001a41",
        "on-tertiary-fixed-variant": "#783100",
        "on-primary-container": "#ffffff",
        "surface-tint": "#005bc0",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#c55500",
        "outline": "#727785",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#9e4300",
        "error": "#ba1a1a",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#ffdbcb",
        "primary-container": "#1a73e8",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#adc7ff",
        "primary-fixed": "#d8e2ff",
        "surface-dim": "#d9dadb",
        "outline-variant": "#c1c6d6",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed-dim": "#c6c4df",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "primary": "#005bbf",
        "secondary-fixed": "#e2e0fc",
        "on-tertiary": "#ffffff",

        // Retro-futuristic tokens
        // Retro-futuristic tokens
        "rf-base": "var(--rf-base, #0A0A1A)",
        "rf-surface": "var(--rf-surface, #0F0F2E)",
        "rf-card": "var(--rf-card, #151530)",
        "rf-cyan": "var(--rf-cyan, #00D4FF)",
        "rf-green": "var(--rf-green, #00FF88)",
        "rf-amber": "var(--rf-amber, #FFB800)",
        "rf-red": "var(--rf-red, #FF3B5C)",
        "rf-cyan-dim": "var(--rf-border, rgba(0, 212, 255, 0.2))",
        "rf-cyan-glow": "var(--rf-glow, rgba(0, 212, 255, 0.3))",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["Space Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        "rf-glow": "0 0 12px rgba(0, 212, 255, 0.3)",
        "rf-glow-lg": "0 0 16px rgba(0, 212, 255, 0.25)",
        "rf-glow-xl": "0 0 24px rgba(0, 212, 255, 0.35)",
        "ambient": "0 8px 32px rgba(25, 28, 29, 0.06)",
        "ambient-lg": "0 12px 40px rgba(0, 91, 191, 0.25)",
      },
      animation: {
        "scan-line": "scanLine 0.3s ease-in-out",
        "fade-in": "fadeIn 0.4s ease-out",
        "count-up": "countUp 1s ease-out",
        "ring-fill": "ringFill 1s ease-out",
      },
      keyframes: {
        scanLine: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "50%": { opacity: "0.5", transform: "translateY(0)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        countUp: {
          "0%": { opacity: "0", transform: "scale(0.8)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        ringFill: {
          "0%": { strokeDashoffset: "176" },
        },
      },
    },
  },
  plugins: [],
}
